#!/bin/sh

# commonFunctions variables
export SUIF_ONLINE_MODE=${SUIF_ONLINE_MODE:-0}
export SUIF_AUDIT_BASE_DIR=${SUIF_AUDIT_BASE_DIR:-"/app/audit"}

# setupFunctions Variables
export SUIF_INSTALL_INSTALLER_BIN=${SUIF_INSTALL_INSTALLER_BIN:-"/tmp/installer.bin"}
export SUIF_INSTALL_INSTALL_DIR=${SUIF_INSTALL_INSTALL_DIR:-"/opt/sag/products"}
export SUIF_INSTALL_SPM_HTTPS_PORT=${SUIF_INSTALL_SPM_HTTPS_PORT:-"9083"}
export SUIF_INSTALL_SPM_HTTP_PORT=${SUIF_INSTALL_SPM_HTTP_PORT:-"9082"}

export SUIF_PATCH_SUM_BOOSTSTRAP_BIN=${SUIF_PATCH_SUM_BOOSTSTRAP_BIN:-"/tmp/sum-boostrap.bin"}

# Specific product setup variables
export SUIF_SETUP_TEMPLATE_IS_LICENSE_FILE=${SUIF_SETUP_TEMPLATE_IS_LICENSE_FILE:-"/tmp/IS-license.xml"}
export SUIF_SETUP_TEMPLATE_MFTSERVER_LICENSE_FILE=${SUIF_SETUP_TEMPLATE_MFTSERVER_LICENSE_FILE:-"/tmp/MFT_Server_license.xml"}

export SUIF_INSTALL_DECLARED_HOSTNAME=${SUIF_INSTALL_DECLARED_HOSTNAME:-"localhost"}

export SUIF_INSTALL_IS_MAIN_HTTP_PORT=${SUIF_INSTALL_IS_MAIN_HTTP_PORT:-"5555"}
export SUIF_INSTALL_MFTSERVER_COMM_PORT=${SUIF_INSTALL_MFTSERVER_COMM_PORT:-"8500"}

export SUIF_MFTGW_URL_PROTOCOL=${SUIF_MFTGW_URL_PROTOCOL:-"http"}
export SUIF_MFTGW_DOMAINNAME=${SUIF_INSTALL_DECLARED_HOSTNAME:-"localhost"}

# We will apply 2 separate templates
export SUIF_DBC4AT_INSTALL_IMAGE_FILE=${SUIF_DBC4AT_INSTALL_IMAGE_FILE:-"/tmp/dbc4at.product.image.zip"}
export SUIF_AT_INSTALL_IMAGE_FILE=${SUIF_AT_NSTALL_IMAGE_FILE:-"/tmp/at.product.image.zip"}

#export SUIF_DBC4AT_PATCH_FIXES_IMAGE_FILE=${SUIF_DBC4AT_PATCH_FIXES_IMAGE_FILE:-"/tmp/dbc4at.fixes.image.zip"}
#export SUIF_AT_PATCH_FIXES_IMAGE_FILE=${SUIF_AT_PATCH_FIXES_IMAGE_FILE:-"/tmp/at.fixes.image.zip"}

# MFT Database
## User MUST provide
#export SUIF_SQLSERVER_HOSTNAME=${SUIF_SQLSERVER_HOSTNAME-:"sql-server1"}
#export SUIF_SQLSERVER_DATABASE_NAME=${SUIF_SQLSERVER_DATABASE_NAME-:"webmethods"}
#export SUIF_SQLSERVER_USER_NAME=${SUIF_SQLSERVER_USER_NAME-:"webmethods"}
#export SUIF_SQLSERVER_PASSWORD=${SUIF_SQLSERVER_PASSWORD-:"webmethods"}

## User MUST provide only IF SUIF_DATABASE_ALREADY_CREATED is not 0
#export SUIF_SQLSERVER_SA_PASSWORD=${SUIF_SQLSERVER_SA_PASSWORD-:"ProvideSaPassword!"}