#!/bin/sh

# caller MUST provide
export SUIF_APIGW_SETTINGS_JSON_FILE=${SUIF_APIGW_SETTINGS_JSON_FILE:-"/tmp/must_give_a_settings_json_file"}

# caller SHOULD provide
export SUIF_APIGW_ADMINISTRATOR_PASSWORD=${SUIF_APIGW_ADMINISTRATOR_PASSWORD:-"manage"}

export SUIF_APIGW_URL_PROTOCOL=${SUIF_APIGW_URL_PROTOCOL:-"http"}
export SUIF_APIGW_DOMAINNAME=${SUIF_APIGW_DOMAINNAME:-"localhost"}
export SUIF_APIGW_SERVICE_PORT=${SUIF_APIGW_SERVICE_PORT:-"5555"}