#!/bin/sh

export SUIF_MFTGW_OLD_ADMINISTRATOR_PASSWORD=${SUIF_MFTGW_OLD_ADMINISTRATOR_PASSWORD:-"manage"}
export SUIF_MFTGW_NEW_ADMINISTRATOR_PASSWORD=${SUIF_MFTGW_NEW_ADMINISTRATOR_PASSWORD:-"manage1"}

export SUIF_MFTGW_URL_PROTOCOL=${SUIF_MFTGW_URL_PROTOCOL:-"http"}
export SUIF_MFTGW_DOMAINNAME=${SUIF_MFTGW_DOMAINNAME:-"localhost"}
export SUIF_MFTGW_SERVICE_PORT=${SUIF_MFTGW_SERVICE_PORT:-"5555"}
