#!/bin/sh

export SUIF_MFTSERVER_OLD_ADMINISTRATOR_PASSWORD=${SUIF_MFTSERVER_OLD_ADMINISTRATOR_PASSWORD:-"manage"}
export SUIF_MFTSERVER_NEW_ADMINISTRATOR_PASSWORD=${SUIF_MFTSERVER_NEW_ADMINISTRATOR_PASSWORD:-"manage1"}

export SUIF_MFTSERVER_URL_PROTOCOL=${SUIF_MFTSERVER_URL_PROTOCOL:-"http"}
export SUIF_MFTSERVER_DOMAINNAME=${SUIF_MFTSERVER_DOMAINNAME:-"localhost"}
export SUIF_MFTSERVER_SERVICE_PORT=${SUIF_MFTSERVER_SERVICE_PORT:-"5555"}
