#!/bin/sh

export SUIF_APIGW_OLD_ADMINISTRATOR_PASSWORD=${SUIF_APIGW_OLD_ADMINISTRATOR_PASSWORD:-"manage"}
export SUIF_APIGW_NEW_ADMINISTRATOR_PASSWORD=${SUIF_APIGW_NEW_ADMINISTRATOR_PASSWORD:-"manage1"}

export SUIF_APIGW_URL_PROTOCOL=${SUIF_APIGW_URL_PROTOCOL:-"http"}
export SUIF_APIGW_DOMAINNAME=${SUIF_APIGW_DOMAINNAME:-"localhost"}
export SUIF_APIGW_SERVICE_PORT=${SUIF_APIGW_SERVICE_PORT:-"5555"}
